### ISSUE TITLE
Domain not handle None object

### ISSUE THREAD

**Issue by reahaas** [python-validators/validators#143]
validators None issue:

code:
```
def validator_test():
    import validators
    if validators.domain(None):
        print("None object is FQDN")
    else:
        print("None object is NOT FQDN")
```

error
```
Traceback (most recent call last):
  File "/home/vagrant/scadafence/rea-helper.py", line 49, in <module>
    main()
  File "/home/vagrant/scadafence/rea-helper.py", line 45, in main
    validator_test()
  File "/home/vagrant/scadafence/rea-helper.py", line 33, in validator_test
    if validators.domain(None):
  File "</home/vagrant/scadafence/venv/local/lib/python2.7/site-packages/decorator.pyc:decorator-gen-2>", line 2, in domain
  File "/home/vagrant/scadafence/venv/local/lib/python2.7/site-packages/validators/utils.py", line 83, in wrapper
    value = func(*args, **kwargs)
  File "/home/vagrant/scadafence/venv/local/lib/python2.7/site-packages/validators/domain.py", line 60, in domain
    return pattern.match(to_unicode(value).encode('idna').decode('ascii'))
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by reahaas** [comment]
Of course, I can check it before using the validators, but the validator already checks it, so why not to handle the "None" case?
After all, None is not an FQDN...

**Comment by reahaas** [comment]
a solution may be in the catch statement:
```
try:
        return pattern.match(to_unicode(value).encode('idna').decode('ascii'))
    except (UnicodeError, AttributeError) as e:
        return False
```

**Comment by reahaas** [comment]
Open new PR: 
https://github.com/kvesteri/validators/pull/144

**Comment by reahaas** [comment]
I looked at other validators (not only the domain) and it seems that all of them don't handling the "None" as input...
If this PR will be approved I can also fix all the validators to handle the "None" case...
